<?xml version="1.0"?>
<package format="3">
  <name>structure_core</name>
  <version>0.1.0</version>
  <description>ROS2 driver node for Occipital Structure Core.</description>

  <maintainer email="noone@noone.com">Not Maintained</maintainer>
  <author email="chad@chaddev.com">Chad Rockey</author>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>libusb-1.0</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
